/**
 * AUTO-GENERATED FILE @ Wed, 10 Nov 2021 07:39:14 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.0.0.12
 * $ schemats generate postgres://username:password@localhost:5432/alpaca_salon -s public
 *
 */

export interface hashtag {
  id: number
  creation_time: Date
  name: string
}

export interface comment {
  id: number
  creation_time: Date
  modification_time: Date
  contents: string
  post_id: number
  user_id: string
  comment_id?: number | null
}

export interface user {
  id: string
  creation_time: Date
  modification_time: Date
  unique_name: string
  nickname: string
  name?: string | null
  email?: string | null
  phone?: string | null
  birth?: Date | null
  bio?: string | null
  image_url?: string | null
  google_oauth?: string | null
  naver_oauth?: string | null
  kakao_oauth?: string | null
  password_hash: string
  validation_time: Date
}

export interface post {
  id: number
  creation_time: Date
  modification_time: Date
  category: number
  title: string
  contents: string
  user_id: string
}

export interface event {
  id: number
  creation_time: Date
  modification_time: Date
  title: string
  category: number
  location: string
  image_url: string
  contents: string
  is_available: boolean
  date?: string | null
  price?: number | null
  user_id: string
}

export interface user_x_liked_comment {
  user_id: string
  comment_id: number
  creation_time: Date
}

export interface post_x_hashtag {
  post_id: number
  hashtag_id: number
  creation_time: Date
}

export interface user_x_liked_post {
  user_id: string
  post_id: number
  creation_time: Date
}

export interface Tables {
  hashtag: hashtag
  comment: comment
  user: user
  post: post
  event: event
  user_x_liked_comment: user_x_liked_comment
  post_x_hashtag: post_x_hashtag
  user_x_liked_post: user_x_liked_post
}
